/** @format */

import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub
} from 'react-icons/ai'
import Image from 'next/image'
import mah from "../public/mah-dev.jpg"
import design3d from "../public/design3d.png"
import codedeveloping from "../public/codedeveloping.jpg"
import uilibraries from "../public/uilibraries.jpg"
import filtersearchsort from "../public/filtersearchsort.jpg"
import shoppingcart from "../public/shoppingcart.jpg"
import todolist from "../public/todolist.jpg"
import contactList from "../public/contactList.jpg"
import ExpenseTracker from "../public/ExpenseTracker.jpg"
import panelAdmin from "../public/panelAdmin.jpg"
import { useState } from 'react'
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode? "dark":""}>
      <Head>
        <title>Mahdi Motahhari Portofolio </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-Burtons'>developedbymahdi</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill  className='cursor-pointer text-2xl' onClick={()=> setDarkMode(!darkMode)} />
              </li>
              <li>
                <a
                  className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                  href='#'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
              Mahdi bidgoli
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl mx-w-lg mx-auto'>
              Freelancer providing services for programmimg, multi-languages app
              and design content needs. Join me and let's get craking!
            </p>
          </div>

          <div className='text-5xl flex justify-center space-x-20 py-3'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className='relative mx-auto rounded-full w-40 h-40 mt-20 overflow-hidden md:w-96 md:h-96'>
            <Image src={mah} layout="fill" objectFit='cover' className="rounded-full w-40 h-40" />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1' >
            services I offer
            </h3>
            <p className='text-md py-2 leading-8 text-gray-800 '>
              Since the beginning of my journey as freelancer designinng
              developer, I was interested in remote work
              &nbsp;<span className='text-teal-500' >agencies</span>
              &nbsp;
              consulted for
              &nbsp;<span className='text-teal-500'>startups </span>
              
              and collaborated with
              <span className='text-teal-500'> Arabic Compenies</span> as well as other internationall compenies to create digital product
                for both business and consumer use.
               
              
            </p>
            
          </div>
          <div className=' lg:flex gap-10 space-x-6'>
            <div className='relative text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white' >
              <Image src={design3d} width={220} height={220} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p>Creating element designs suited for your needs following core design theory</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>photoshop</p>
              <p className='text-gray-800 py-1'>illustrater</p>
              <p className='text-gray-800 py-1'> figma</p>
            </div>
            <div className='relative text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={codedeveloping} width={220} height={200} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful Designs</h3>
              <p>Creating element designs suited for your needs following core design theory</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>photoshop</p>
              <p className='text-gray-800 py-1'>illustrater</p>
              <p className='text-gray-800 py-1'> figma</p>
            </div>
            <div className='relative text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={uilibraries} width={240} height={200} />
              <h3 className='text-lg font-medium pt-8 pb-2'>UI Libraries</h3>
              <p>Creating element designs suited for your needs following core design theory</p>
              <h4 className='py-4 text-teal-600'>Libraries I use</h4>
              <p className='text-gray-800 py-1'>AntDesign</p>
              <p className='text-gray-800 py-1'>Material UI</p>
              <p className='text-gray-800 py-1'> React-icons</p>
            </div>
          </div>
        </section>
        <section>
          <div>
          <h3 className='text-3xl py-1' >
           Portfolio
          </h3>
          <p className='text-md py-2 leading-8 text-gray-800 '>
              Since the beginning of my journey as freelancer designinng
              developer, I was interested in remote work
              &nbsp;<span className='text-teal-500' >agencies</span>
              &nbsp;
              consulted for
              &nbsp;<span className='text-teal-500'>startups </span>
              
              and collaborated with
              <span className='text-teal-500'> Arabic Compenies</span> as well as other internationall compenies to create digital product
                for both business and consumer use.
               
              
            </p>
        
          </div>
          <div className='flex flex-col gap-10 space-x-10 space-y-10 py-10 lg:flex-row flex-wrap'>
            <div className='basis-1/3 flex-1'><Image src={filtersearchsort} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />Filter & search & sort</div>
            <div className='basis-1/3 flex-1'><Image src={shoppingcart} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>Shopping cart</div>
            <div className='basis-1/3 flex-1'><Image src={todolist} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/> Todolist</div>
            <div className='basis-1/3 flex-1'><Image src={contactList} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>ContactList</div>
            <div className='basis-1/3 flex-1'><Image src={ExpenseTracker} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>ExpenseTracker</div>
            <div className='basis-1/3 flex-1'><Image src={panelAdmin} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>Panel Admin</div>
            
          </div>
          </section>
      </main>
    </div>
  )
}
